version: 1.8.{build}
branches:
  only:
  - master
image: Visual Studio 2017
environment:
  my_variable:
    secure: Qpq/4cyuTUzmt/r4HsQxioG6WXrZSK3mzVq5iUJC2RI=
  NugetApiKey:
    secure: Ar6IQ+BxCwH6r8SgUB+6wzlWRD0Y+pkW+eFhZUTsF/yb5SyfEcDV7RNzzbGGe26Y
  ChocolateyApiKey:
    secure: mXmzLqgFyDEjGRcE4UpqwqOXmdiCm9HwJ2V3LzSAz06GL1OaBDoTzidw7Rly+UHk
  GitHubApiKey:
    secure: N83nQZ/QQVqpRnl0D6F/xSbKjn062y07JdskpUpbWryMY2JDo4Be9lUXmob+xcOO
build_script:
- cmd: PowerShell.exe -NoProfile -ExecutionPolicy Bypass -Command "& '.\build.ps1' --target Clean Pack Publish CreateSetup PublishToAppveyor ChangeVersionNumber --Configuration Release"
test: off
